import io

from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import letter
from reportlab.pdfbase.pdfmetrics import stringWidth
from reportlab.pdfgen import canvas

BG = HexColor("#181816")
CARD = HexColor("#221f1c")
BORDER = HexColor("#3a3631")
TEXT = HexColor("#ece8e1")
MUTED = HexColor("#9c968a")
ACCENT = HexColor("#cc785c")

MARGIN = 40


def _sanitize(text: str) -> str:
    return (text or "").replace("→", "->").replace("→", "->")


def _wrap(text: str, font: str, size: float, max_width: float) -> list[str]:
    words = _sanitize(text).split()
    lines: list[str] = []
    current = ""
    for word in words:
        candidate = f"{current} {word}".strip()
        if stringWidth(candidate, font, size) <= max_width:
            current = candidate
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


def _ellipsize(line: str, font: str, size: float, max_width: float) -> str:
    while line and stringWidth(line + "…", font, size) > max_width:
        line = line[:-1].rstrip()
    return line + "…"


def _draw_card(c: canvas.Canvas, x: float, y: float, w: float, h: float, title: str, body: str):
    c.setFillColor(CARD)
    c.setStrokeColor(BORDER)
    c.roundRect(x, y, w, h, 8, fill=1, stroke=1)
    c.setFillColor(ACCENT)
    c.rect(x, y, 3, h, fill=1, stroke=0)

    pad = 14
    c.setFillColor(ACCENT)
    c.setFont("Helvetica-Bold", 8)
    c.drawString(x + pad, y + h - 16, title.upper())

    c.setFillColor(TEXT)
    body_font, body_size, leading = "Helvetica", 8.3, 11
    max_width = w - 2 * pad
    lines = _wrap(body, body_font, body_size, max_width)
    max_lines = max(1, int((h - 28) // leading))

    shown = lines[:max_lines]
    if len(lines) > max_lines and shown:
        shown[-1] = _ellipsize(shown[-1], body_font, body_size, max_width)

    c.setFont(body_font, body_size)
    ty = y + h - 30
    for line in shown:
        c.drawString(x + pad, ty, line)
        ty -= leading


def _draw_questions_card(c: canvas.Canvas, x: float, y: float, w: float, h: float, questions: list[str]):
    c.setFillColor(CARD)
    c.setStrokeColor(BORDER)
    c.roundRect(x, y, w, h, 8, fill=1, stroke=1)
    c.setFillColor(ACCENT)
    c.rect(x, y, 3, h, fill=1, stroke=0)

    pad = 16
    c.setFillColor(ACCENT)
    c.setFont("Helvetica-Bold", 9)
    c.drawString(x + pad, y + h - 18, "QUESTIONS TO ASK")

    body_font, body_size, leading = "Helvetica", 8.6, 12
    max_width = w - 2 * pad - 14
    ty = y + h - 36
    for question in questions[:4]:
        c.setFillColor(ACCENT)
        c.setFont(body_font, body_size)
        c.drawString(x + pad, ty, "•")
        c.setFillColor(TEXT)
        lines = _wrap(question, body_font, body_size, max_width)[:2]
        for i, line in enumerate(lines):
            c.drawString(x + pad + 14, ty, line)
            ty -= leading
        ty -= 4


def generate_pdf(company_name: str, job_title: str, result: dict) -> bytes:
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    width, height = letter

    c.setFillColor(BG)
    c.rect(0, 0, width, height, fill=1, stroke=0)

    c.setFillColor(TEXT)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(MARGIN, height - MARGIN - 16, f"{company_name} — {job_title}")
    c.setFillColor(MUTED)
    c.setFont("Helvetica", 9)
    c.drawString(MARGIN, height - MARGIN - 32, "Interview Briefing")
    c.setFillColor(ACCENT)
    c.rect(MARGIN, height - MARGIN - 42, width - 2 * MARGIN, 1.2, fill=1, stroke=0)

    grid_top = height - MARGIN - 56
    col_w = (width - 2 * MARGIN - 16) / 2
    row_h = 95
    gap = 16

    cards = [
        ("What they're looking for", result.get("candidate_profile", "")),
        ("Culture", result.get("culture", "")),
        ("Experience level", result.get("experience_level", "")),
        ("Environment", result.get("environment", "")),
        ("The company", result.get("company_explainer", "")),
        ("Locations", result.get("locations", "")),
    ]

    last_row_bottom = grid_top
    for i, (title, body) in enumerate(cards):
        col, row = i % 2, i // 2
        x = MARGIN + col * (col_w + 16)
        y = grid_top - row_h - row * (row_h + gap)
        _draw_card(c, x, y, col_w, row_h, title, body)
        last_row_bottom = min(last_row_bottom, y)

    q_height = 190
    q_y = last_row_bottom - gap - q_height
    _draw_questions_card(c, MARGIN, q_y, width - 2 * MARGIN, q_height, result.get("questions_to_ask", []))

    c.setFillColor(MUTED)
    c.setFont("Helvetica", 7)
    c.drawString(MARGIN, MARGIN - 14, "Generated by Interview Prep")

    c.showPage()
    c.save()
    return buf.getvalue()
